/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Examen;

import deepspace.EnemyStarShip;
import deepspace.EnemyToUI;
import deepspace.NumericDamageToUI;
import deepspace.SpecificDamageToUI;

/**
 *
 * @author mariogmarq
 */
public class Enemy extends javax.swing.JPanel {

    /** Creates new form Enemy */
    public Enemy() {
        initComponents();
    }
    
    void updateComponent(EnemyToUI e) {
        valorNombre.setText(e.getName());
        valorDefensa.setText(Float.toString(e.getShieldPower()));
        valorFuego.setText(Float.toString(e.getAmmoPower()));
        
        panelDamage.removeAll();
        if(e.getDamage() instanceof SpecificDamageToUI){
            SpecificDamageView s = new SpecificDamageView();
            s.updateComponent((SpecificDamageToUI)e.getDamage());
            panelDamage.add(s);
        } else {
            NumericView s = new NumericView();
            s.updateComponent((NumericDamageToUI)e.getDamage());
            panelDamage.add(s);
        }
        
        revalidate();
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDamage = new javax.swing.JPanel();
        valorDefensa = new javax.swing.JLabel();
        etiquetaEnemigo = new javax.swing.JLabel();
        valorNombre = new javax.swing.JLabel();
        etiquetaFuego = new javax.swing.JLabel();
        valorFuego = new javax.swing.JLabel();
        etiquetaDefensa = new javax.swing.JLabel();

        panelDamage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valorDefensa.setText("defensa");

        etiquetaEnemigo.setText("Enemigo:");

        valorNombre.setText("nombre");

        etiquetaFuego.setText("Potencia de fuego: ");

        valorFuego.setText("fuego");

        etiquetaDefensa.setText("Potencia de defensa: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaFuego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorFuego))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaDefensa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorDefensa)))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEnemigo)
                    .addComponent(valorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFuego)
                    .addComponent(valorFuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDefensa)
                    .addComponent(valorDefensa))
                .addGap(18, 18, 18)
                .addComponent(panelDamage, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaDefensa;
    private javax.swing.JLabel etiquetaEnemigo;
    private javax.swing.JLabel etiquetaFuego;
    private javax.swing.JPanel panelDamage;
    private javax.swing.JLabel valorDefensa;
    private javax.swing.JLabel valorFuego;
    private javax.swing.JLabel valorNombre;
    // End of variables declaration//GEN-END:variables

}
