/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.ShieldToUI;
import deepspace.SpaceStationToUI;
import deepspace.WeaponToUI;

/**
 *
 * @author mario
 */
public class CurrentStation extends javax.swing.JPanel {

    /**
     * Creates new form CurrentStation
     */
    public CurrentStation() {
        initComponents();
    }
    
    public void updateComponent(SpaceStationToUI s) {
        if(s.getPendingDamage()!=null) {
            damage.updateComponent(s.getPendingDamage());
        } else {
            damage.nilDamage();
        }
        
        //Update weapons
        panelArmas.removeAll();
        for(WeaponToUI w: s.getWeapons()) {
            View.GUI.Weapon cmp = new Weapon();
            cmp.updateComponent(w);
            cmp.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            panelArmas.add(cmp);
        }
        
        //Update shields
        panelEscudos.removeAll();
        for(ShieldToUI shield: s.getShieldBoosters()) {
            View.GUI.Shield cmp = new Shield();
            cmp.updateComponent(shield);
            cmp.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            panelEscudos.add(cmp);
        }
        
        panelHangar.removeAll();
        for(WeaponToUI w: s.getHangar().getWeapons()){
            View.GUI.Weapon cmp = new Weapon();
            cmp.updateComponent(w);
            cmp.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            panelHangar.add(cmp);
        }
        for(ShieldToUI shield: s.getHangar().getShieldBoosters()){
            View.GUI.Shield cmp = new Shield();
            cmp.updateComponent(shield);
            cmp.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            panelHangar.add(cmp);
        }
        
        
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        damage = new View.GUI.Damage();
        panelArmas = new javax.swing.JPanel();
        panelEscudos = new javax.swing.JPanel();
        panelHangar = new javax.swing.JPanel();

        damage.setBorder(javax.swing.BorderFactory.createTitledBorder("Castigo pendiente\n"));

        panelArmas.setBorder(javax.swing.BorderFactory.createTitledBorder("Armas"));

        panelEscudos.setBorder(javax.swing.BorderFactory.createTitledBorder("Escudos"));

        panelHangar.setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelHangar.getAccessibleContext().setAccessibleName("Hangar");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.GUI.Damage damage;
    private javax.swing.JPanel panelArmas;
    private javax.swing.JPanel panelEscudos;
    private javax.swing.JPanel panelHangar;
    // End of variables declaration//GEN-END:variables
}
