/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.DamageToUI;

/**
 *
 * @author mario
 */
public class Damage extends javax.swing.JPanel {

    /**
     * Creates new form Damage
     */
    public Damage() {
        initComponents();
    }
    
    public void updateComponent(DamageToUI d) {
        valorEscudos.setText(Integer.toString(d.getNShields()));
        valorArmas.setText(d.getWeaponInfo());
        
        //refresh
        revalidate();
        repaint();
    }
    
    public void nilDamage() {
        valorEscudos.setText("0");
        valorArmas.setText("0");
        
        //refresh
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaEscudos = new javax.swing.JLabel();
        valorEscudos = new javax.swing.JLabel();
        etiquetaArmas = new javax.swing.JLabel();
        valorArmas = new javax.swing.JLabel();

        etiquetaEscudos.setText("Escudos:");

        valorEscudos.setText("0");

        etiquetaArmas.setText("Armas:");

        valorArmas.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaEscudos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorEscudos)
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaArmas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorArmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEscudos)
                    .addComponent(valorEscudos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaArmas)
                    .addComponent(valorArmas))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaArmas;
    private javax.swing.JLabel etiquetaEscudos;
    private javax.swing.JLabel valorArmas;
    private javax.swing.JLabel valorEscudos;
    // End of variables declaration//GEN-END:variables
}
