/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.EnemyToUI;

/**
 *
 * @author mario
 */
public class Enemy extends javax.swing.JPanel {

    /**
     * Creates new form Enemy
     */
    public Enemy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaEnemigo = new javax.swing.JLabel();
        valorNombre = new javax.swing.JLabel();
        etiquetaFuego = new javax.swing.JLabel();
        valorFuego = new javax.swing.JLabel();
        etiquetaDefensa = new javax.swing.JLabel();
        valorDefensa = new javax.swing.JLabel();
        damage = new View.GUI.Damage();
        loot = new View.GUI.Loot();

        etiquetaEnemigo.setText("Enemigo:");

        valorNombre.setText("nombre");

        etiquetaFuego.setText("Potencia de fuego: ");

        valorFuego.setText("fuego");

        etiquetaDefensa.setText("Potencia de defensa: ");

        valorDefensa.setText("defensa");

        damage.setBorder(javax.swing.BorderFactory.createTitledBorder("Castigo\n"));
        damage.setToolTipText("Castigo");
        damage.setName("Damage"); // NOI18N

        loot.setBorder(javax.swing.BorderFactory.createTitledBorder("Botin"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaFuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorFuego))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaDefensa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorDefensa))
                    .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEnemigo)
                    .addComponent(valorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFuego)
                    .addComponent(valorFuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDefensa)
                    .addComponent(valorDefensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(loot, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        damage.getAccessibleContext().setAccessibleName("Castigo");
    }// </editor-fold>//GEN-END:initComponents

    public void updateComponent(EnemyToUI e) {
        valorNombre.setText(e.getName());
        valorFuego.setText(Float.toString(e.getAmmoPower()));
        valorDefensa.setText(Float.toString(e.getShieldPower()));
        damage.updateComponent(e.getDamage());
        loot.updateComponent(e.getLoot());
        
        
        //Update
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.GUI.Damage damage;
    private javax.swing.JLabel etiquetaDefensa;
    private javax.swing.JLabel etiquetaEnemigo;
    private javax.swing.JLabel etiquetaFuego;
    private View.GUI.Loot loot;
    private javax.swing.JLabel valorDefensa;
    private javax.swing.JLabel valorFuego;
    private javax.swing.JLabel valorNombre;
    // End of variables declaration//GEN-END:variables
}
