/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author mario
 */
public class Loot extends javax.swing.JPanel {

    /**
     * Creates new form Loot
     */
    public Loot() {
        initComponents();
    }
    
    public void updateComponent(LootToUI l) {
        valorArmas.setText(Integer.toString(l.getnWeapons()));
        valorCombustible.setText(Integer.toString(l.getnSupplies()));
        valorEscudos.setText(Integer.toString(l.getnShields()));
        valorMedallas.setText(Integer.toString(l.getnMedals()));
        valorHangar.setText(Integer.toString(l.getnHangars()));
        
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaArmas = new javax.swing.JLabel();
        etiquetaEscudos = new javax.swing.JLabel();
        etiquetaHangar = new javax.swing.JLabel();
        etiquetaCombustible = new javax.swing.JLabel();
        etiquetaMEdallas = new javax.swing.JLabel();
        valorArmas = new javax.swing.JLabel();
        valorEscudos = new javax.swing.JLabel();
        valorHangar = new javax.swing.JLabel();
        valorCombustible = new javax.swing.JLabel();
        valorMedallas = new javax.swing.JLabel();

        etiquetaArmas.setText("Armas:");

        etiquetaEscudos.setText("Escudos:");

        etiquetaHangar.setText("Hangar:");

        etiquetaCombustible.setText("Combustible:");

        etiquetaMEdallas.setText("Medallas:");

        valorArmas.setText("jLabel1");

        valorEscudos.setText("jLabel1");

        valorHangar.setText("jLabel1");

        valorCombustible.setText("jLabel1");

        valorMedallas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaArmas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorArmas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaEscudos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorEscudos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaHangar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorHangar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaCombustible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorCombustible))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaMEdallas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorMedallas)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaArmas)
                    .addComponent(valorArmas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEscudos)
                    .addComponent(valorEscudos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaHangar)
                    .addComponent(valorHangar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCombustible)
                    .addComponent(valorCombustible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMEdallas)
                    .addComponent(valorMedallas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaArmas;
    private javax.swing.JLabel etiquetaCombustible;
    private javax.swing.JLabel etiquetaEscudos;
    private javax.swing.JLabel etiquetaHangar;
    private javax.swing.JLabel etiquetaMEdallas;
    private javax.swing.JLabel valorArmas;
    private javax.swing.JLabel valorCombustible;
    private javax.swing.JLabel valorEscudos;
    private javax.swing.JLabel valorHangar;
    private javax.swing.JLabel valorMedallas;
    // End of variables declaration//GEN-END:variables
}
