/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import View.DeepSpaceView;
import java.util.ArrayList;
import controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class MainWindow extends javax.swing.JFrame implements DeepSpaceView{

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        BotonTurno = new javax.swing.JButton();
        botonCombatir = new javax.swing.JButton();
        botonEquipar = new javax.swing.JButton();
        botonDescartar = new javax.swing.JButton();
        botonDescartarHangar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        BotonTurno.setText("Siguiente turno");
        BotonTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTurnoActionPerformed(evt);
            }
        });

        botonCombatir.setText("Combatir");
        botonCombatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCombatirActionPerformed(evt);
            }
        });

        botonEquipar.setText("Equipar");

        botonDescartar.setText("Descartar");

        botonDescartarHangar.setText("Descartar Hangar");
        botonDescartarHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescartarHangarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEquipar)
                .addGap(18, 18, 18)
                .addComponent(botonDescartar)
                .addGap(18, 18, 18)
                .addComponent(botonDescartarHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCombatir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonTurno)
                        .addGap(139, 139, 139)
                        .addComponent(botonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addComponent(botonCombatir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(BotonTurno)
                    .addComponent(botonEquipar)
                    .addComponent(botonDescartar)
                    .addComponent(botonDescartarHangar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Controller.getInstance().finish(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void BotonTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTurnoActionPerformed
        Controller.getInstance().nextTurn();
    }//GEN-LAST:event_BotonTurnoActionPerformed

    private void botonCombatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCombatirActionPerformed
        Controller.getInstance().combat();
    }//GEN-LAST:event_botonCombatirActionPerformed

    private void botonDescartarHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescartarHangarActionPerformed
        Controller.getInstance().discardHangar();
    }//GEN-LAST:event_botonDescartarHangarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    @Override
    public void updateView() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public ArrayList<String> readNamePlayers() {
        NameCapture capture = new NameCapture(this);
        return capture.getNames();
    }

    @Override
    public boolean confirmExitMessage() {
       return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?", "DeepSpace mola mogollon", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }

    @Override
    public void nextTurnNotAllowedMessage() {
        JOptionPane.showMessageDialog(this, "No se puede pasar de turno, a ver si miramos antes de pulsar");
    }

    @Override
    public void lostCombatMessage() {
        JOptionPane.showMessageDialog(this, "Has perdido el combate. Suerte la proxima vez");
    }

    @Override
    public void escapeMessage() {
        JOptionPane.showMessageDialog(this, "Has escapado del combate, has tenido suerte");
    }

    @Override
    public void wonCombatMessage() {
        JOptionPane.showMessageDialog(this, "Menuda paliza le has metido a tu enemigo, has ganado el combate!");
    }

    @Override
    public void wonGameMessage() {
        JOptionPane.showMessageDialog(this, "Has ganado la partida, enseñale a tus amigos a jugar bien anda");
    }

    @Override
    public void conversionMessage() {
        JOptionPane.showMessageDialog(this, "Ganas y te transformas, menudo combo");
    }

    @Override
    public void noCombatMessage() {
        JOptionPane.showMessageDialog(this, "No puedes combatir en este momento");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTurno;
    private javax.swing.JButton botonCombatir;
    private javax.swing.JButton botonDescartar;
    private javax.swing.JButton botonDescartarHangar;
    private javax.swing.JButton botonEquipar;
    private javax.swing.JButton botonSalir;
    // End of variables declaration//GEN-END:variables
}
