/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.WeaponToUI;

/**
 *
 * @author mario
 */
public class Weapon extends javax.swing.JPanel {
    private boolean selected = false;
    /**
     * Creates new form Weapon
     */
    public Weapon() {
        initComponents();
    }
    
    public void updateComponent(WeaponToUI w) {
        valorPotencia.setText(Float.toString(w.getPower()));
        valorUsos.setText(Integer.toString(w.getUses()));
        valorTipo.setText(w.getType().toString());
        selected = false;
        setOpaque(selected);
        
        revalidate();
        repaint();
    }
    
    public boolean getSelected() {
        return selected;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTipo = new javax.swing.JLabel();
        etiquetaPotencia = new javax.swing.JLabel();
        etiquetaUsos = new javax.swing.JLabel();
        valorTipo = new javax.swing.JLabel();
        valorPotencia = new javax.swing.JLabel();
        valorUsos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        etiquetaTipo.setText("Tipo:");

        etiquetaPotencia.setText("Potencia:");

        etiquetaUsos.setText("Usos:");

        valorTipo.setText("jLabel1");

        valorPotencia.setText("jLabel1");

        valorUsos.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaPotencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorPotencia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaUsos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorUsos)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTipo)
                    .addComponent(valorTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPotencia)
                    .addComponent(valorPotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUsos)
                    .addComponent(valorUsos))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaPotencia;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JLabel etiquetaUsos;
    private javax.swing.JLabel valorPotencia;
    private javax.swing.JLabel valorTipo;
    private javax.swing.JLabel valorUsos;
    // End of variables declaration//GEN-END:variables
}
